### ISSUE TITLE
Graph representations

### ISSUE THREAD

**Issue by danieldk** [danieldk/conllx-rs#4]
cc: @sebpuetz, @divefish

Since many downstream tasks need a graph representation of the CoNLL-X data, it would great if this crate could provide that. However, there are many different approaches, and we should hash them out a bit more.

Relevant to the discussion of different approaches is how the graph representation relates to `Vec<Token>`.

1. A conversion of `Vec<Token>` to the graph representation is provided.

  Advantages:

  * No API changes.
  * Simple representation that works well tasks where syntax is irrelevant (tagging, etc.).

  Disadvantages:

  * Requires conversion.
  * Multiple representations in the same crate.
  * The token indices and `head()`/`p_head()` indices mismatch.
  * Needs to own tokens for the graph to be usefully mutable.
  * Probably needs its own `Token` type, otherwise `head()`/`p_head()` and the graph could become inconsistent.

2. The graph representation becomes the representation of CoNLL-X sentences.

  Advantages:

  * A single representation, no conversions.
  * The standard representation is the representation that many downstream tasks use.

  Disadvantages:

  * large API change.
  * could be awkward for token-oriented tasks if no direct indexing of tokens is provided.
  * will (depending on the implementation) be less efficient to construct.

3. Let the user decide the representation and provide `read_to_graph()` and `read_to_vec()` on the ReadSentence trait. (@sebpuetz )

Benefits:

* not breaking the current API
* no required conversion but could still be provided through From and Into

Disadvantages:

* multiple Token types would be required, some of this could probably be alleviated through traits/type parameters
* could be confusing to have two methods/representations in parallel

# Graph representations

## Cheap hack: prepend root to `Vec<Token>`

A very simple approach could just prepend its sentence with the artificial root token. `head()`/`p_head()` could then be used to directly index into the graph.

Advantages:

* Simple change
* As fast to construct as the current representation.

Disadvantages:

* Breaks APIs in an ugly way, because there is existing code that assumes that the indices are off-by-one. If we go this path, the `Vec` should probably be wrapped in another type to force downstream to update code. Also, `Token` should probably become an `enum` that provides a variant for the root.
* Cannot benefit from existing functions from a crate such as `petgraph`.

## `petgraph`

This approach would use the `petgraph` crate and use a type such as `Digraph<Token, DepRel>`. `Token` would then not contain dependency relations anymore. `DepRel` would be an enum for projective and non-projective relations.

Benefits:

* Probably not much slower than the current representation --- node and edge insertions are O(1).
* The user gets to leverage all the functionality and algorithms of `petgraph`.

Downsides:

* Large API change.
* How do we compare two sentences for equality? This is now used a lot in e.g. unit tests. Graph isomorpism is NP. And I think there is no way to force in the type system that the graph is a e.g. a tree  or has ordered vertices with in-degree 1 in `petgraph`.
* The user could turn the dependency tree into a graph that is not a tree. How do we serialize such cases to CoNLL-X again?

## Constrained graph

In this approach, we would create our own representation. It would be similar to approach 1, except that we would separate the dependencies from the tokens. So the structure would be something like:

```rust
struct DependencyGraph {
  tokens: Vec<Node>,
  deprels: Vec<Option<(usize, String)>>,
  p_deprels: Vec<Option<(usize, String)>>,
}

enum Node {
  Root,
  Token {
    // ... the usual fields, but no head/head_rel/p_head/p_head_rel.
  },
}
```

Benefits:

* Nearly the same efficiency as the current representation.
* Tokens are separated from dependency relations.
* Not as confusing as approach 1 in having nearly the same representation.

Disadvantages:

* Cannot benefit from existing functions from a crate such as `petgraph`. Though I guess that we could try to implement some of the `petgraph` traits.
* Somewhat large API change.

**Comment by sebpuetz** [comment]
>     1. A conversion of `Vec<Token>` to the graph representation is provided.
>     [ ...]
>     2. The graph representation becomes the representation of CoNLL-X sentences.
> 
Maybe a third option could be added as an in-between solution:
3. Let the user decide the representation and provide `read_to_graph()` and `read_to_vec()` on the `ReadSentence` trait.

Benefits:
- not breaking the current API
- no required conversion but could still be provided through `From` and `Into`

Disadvantages:

- multiple `Token` types would be required, some of this could probably be alleviated through traits/type parameters
- could be confusing to have two methods/representations in parallel

> # Graph representations
> ## Cheap hack: prepend root to `Vec<Token>`
> 
> A very simple approach could just prepend its sentence with the artificial root token. `head()`/`p_head()` could then be used to directly index into the graph.
 
I don't really like this approach since this only shifts the problem from having to handle the offset to having to handle a dummy root token when iterating through the sentence.

> ## `petgraph`
> 
> This approach would use the `petgraph` crate and use a type such as `Digraph<Token, DepRel>`. `Token` would then not contain dependency relations anymore. `DepRel` would be an enum for projective and non-projective relations.

Maybe an enum could also be used to mark the `Token`s as `Token` and `Root`.
Benefits:
- not having to create a dummy token
- code is more verbose, handling `Root` is clearer than handling `NodeIndex(0)` or a dummy `Token`

Disadvantage:
- accessing the `Token`s requires matching

> Downsides:
> 
>     * Large API change.
> 
>     * How do we compare two sentences for equality? This is now used a lot in e.g. unit tests. Graph isomorpism is NP. And I think there is no way to force in the type system that the graph is a e.g. a tree  or has ordered vertices with in-degree 1 in `petgraph`.
>
>     * The user could turn the dependency tree into a graph that is not a tree. How do we serialize such cases to CoNLL-X again?

I can't add much to the equality issue but I wonder how often it is necessary in practice to compare two dependency graphs.
The last issue boils down to the user can mess up the sentence. But to my understanding this is also possible with the `Vec<Token>` representation. If a `Token` is inserted or removed the indices of the dependency relations are invalidated. Circular dependency graphs don't have an impact on the serialization here but are still not the desired output.
The `Graph` representation would break in a slightly different way. While the indices for the dependency relations could easily be restored the word order would get messed up through insertion/deletion. I think the indices into the graph are the only representation of the original sentence's word order. Unless there is a way to insert with a specific `NodeIndex` while mutating the other indices (I'm pretty sure that's impossible) we can only append to the end of the sentence.
Serialization and conversion into `Vec<Token>` should in my opinion just consist of iterating over the Nodes and using the incoming edge to retrieve the `head` and `dep_rel`, leaving it to the user to not invalidate the sentence. Equality would could be handled in the same naive way.
It would also be fairly cheap to verify the single headedness 
```Rust
let mut edges = g.edges_directed(idx, Incoming);
let edge = edges.next();
assert_eq!(edges.next(), None);
```

**Comment by danieldk** [comment]
*I can't add much to the equality issue but I wonder how often it is necessary in practice to compare two dependency graphs.*

Unit tests :). Both the basic unit tests and the tests for projectivization/deprojectivization.

*The last issue boils down to the user can mess up the sentence. But to my understanding this is also possible with the Vec<Token> representation. If a Token is inserted or removed the indices of the dependency relations are invalidated. Circular dependency graphs don't have an impact on the serialization here but are still not the desired output.*

Indeed. Cyclic graphs can be produced. And this has happened sometimes before, this also led to the introduction of the `conllx-cycle` utility in `conllx-utils`. Some programs will get stuck in an infinite loop because they don't expect a graph with cycles. This could be avoided by using a data structure that is guaranteed to be a tree.

Token insertion and deletion is a genuine application and indeed leads to bugs when you are not careful. E.g. we do this in:

https://github.com/sfb833-a3/adjn/blob/master/adjn-utils/src/bin/coalesce-adj-n.rs

But there we have the benefit that the dependency layers are not necessary and are explicitly cleared. But I see other applications where you'd want the dependency relations (e.g. coalescing p + pobj). I guess that this may an extra desideratum: the possibility of adding/removing tokens without relation invalidation.

*The Graph representation would break in a slightly different way.*

Well, and since Graph provides more freedom, there are more ways to break things. E.g. introducing multi-headedness.

*Unless there is a way to insert with a specific NodeIndex while mutating the other indices (I'm pretty sure that's impossible) we can only append to the end of the sentence.*

It seems so.

**Comment by danieldk** [comment]
I have thought a bit more about cycles: we should be able to represent them. The input CoNLL-X is the ground truth, and we want to be able to represent every CoNLL-X file.

So, I think the *constrained graph* is the very least that we need. Token insertions/removals would be possible in this representation, but it would effectively an *O(n)* operation (we need check all the dependency relations for invalidation). That may be acceptable, since it is not a common operation.

Another facet that I didn't really cover in the initial post is that the current representation and the *constrained* graph makes it cheap to traverse from tokens to their ancestors, but not in the other direction.

Another observation is that we could get the best of both worlds using an undirected graph/tree with boxed nodes and then storing a separate array to provide constant indexing to the nodes. Something along the lines of:

~~~rust
struct Node {
  parent: Weak<Node>,
  children: Vec<Rc<Node>>,
  token: Token,
}

struct LinearOrder(Vec<Rc<Node>);
~~~

Introducing tokens would be easy, they could just be inserted into the `Vec`. Since the nodes/tokens are at fixed memory addresses, insertion does not change anything to the existing nodes/tokens. But this introduces even more boxing + reference counting.

**Comment by sebpuetz** [comment]
Additional to invalidating the word order there is also the issue how to handle the incoming/outgoing edges and neighbors. Just removing a node would result in having broken up the graph and removing some dependency edge(s).

I think to maintain linear order there would be a solution through explicitly storing the original position in a field of the token. Removal would then entail to iterate over all Nodes and decrement the index for all nodes with higher indices. The downside would be completely giving up the relevance of the graph indices.

Handling the neighbors and edges is a lot less straight forward. I don't think there is any kind of expected behavior when removing a token wrt. a dependency graph. Just re-attaching child nodes at the parent node with one of the edges seems at least somewhat odd to me. Not re-attaching them at all results in a disconnected graph which would probably mess up a number of things downstream.

**Comment by danieldk** [comment]
> I think to maintain linear order there would be a solution through explicitly storing the original position in a field of the token. Removal would then entail to iterate over all Nodes and decrement the index for all nodes with higher indices. The downside would be completely giving up the relevance of the graph indices.

And indexing on tokens becomes *O(n)* rather than *O(1)*.

> Handling the neighbors and edges is a lot less straight forward. I don't think there is any kind of expected behavior when removing a token wrt. a dependency graph. Just re-attaching child nodes at the parent node with one of the edges seems at least somewhat odd to me. Not re-attaching them at all results in a disconnected graph which would probably mess up a number of things downstream.

True, but disconnected graphs can already occur in CoNLL-X data, so ideally downstream users should verify it when they need stronger invariants. Of course, once we have a graph representation we could provide some useful methods such as `is_acyclic()` or `is_tree()`. Or reuse those from `petgraph`.

As for the default behavior of removal, I think it should be the simplest primitive operation: remove without reattachment. The user can always implement custom behaviors. A benefit over the current situation would be at least that the existing relations are still valid.

**Comment by sebpuetz** [comment]
My previous point about handling edges and neighbours is only relevant when direct access to the graph is restricted in some way. If the user can directly mutate the underlying graph it would be at their discretion how to handle these cases.
Considering that we are trying to find a way to keep the mutation somewhat safe we would probably want to encapsulate the graph in some way.

> And indexing on tokens becomes O(n) rather than O(1).

Indexing on tokens in the sense of trying to retrieve a token with a specific index from the underlying sentence? 
We might be able to mitigate this through some kind of adjacency array, e.g. `Vec<NodeIndex>` where the index into the array refers to the position in the sentence?

**Comment by danieldk** [comment]
The primary thing that keeps nagging me with the non-petgraph variations is that probably we'll end up converting them to a `petgraph` `Graph` anyway, because `petgraph` is so powerful. So, what we could do is make a type:

~~~rust
pub enum DepNode {
  Root,
  Token {
    // ...
  },
}

pub struct DepGraph(DiGraph<DepNode, DepRel>);
~~~

Note that the inner digraph is not public. `DepGraph` would then provide a very limited set of operations: no token additions/removals. The parent of a token can be set, but this will remove the current head (to avoid multi-headedness, etc.). Then we provide the methods:

~~~rust
fn into_inner(self) -> DiGraph<DepNode, DepRel> {
  self.0
}

fn inner() -> &DiGraph<DepNode, DepRel> {
  &self.0
}

~~~

`into_inner` allows users to get out the `DiGraph` in case they want to do something that cannot be done with the restrictive `DepGraph` methods. The move ensures that the user cannot modify the graph, breaking invariants. Alternatively, they can get an immutable reference to the inner graph.

Then we could also provide a constructor

~~~rust
fn try_from_digraph(digraph: DiGraph<DepNode, DepRel>) -> Result<Self, DepGraphError> {
  // ...
}
~~~

which would move the digraph into `DepGraph`, iff all the variants of the dependency graph hold (max in-degree of 1, etc.), otherwise it would return `Err`. This would allow people to do a round-trip if they want to store the result as CoNLL-X again.

**Comment by sebpuetz** [comment]
This looks like a nice solution, although if I'm understanding this correctly it would only ensure validity of the dependency trees inside of Rust-land. A malformed `DepGraph` could still be introduced through a file unless we do these (rather expensive) checks on every constructed graph.
There might still be a problem with verifying the word order. If a user mutated the underlying `DiGraph` through insertion/deletion there is no way to figure out the correct order for this sentence when constructing a `DepGraph`.

**Comment by danieldk** [comment]
> This looks like a nice solution, although if I'm understanding this correctly it would only ensure validity of the dependency trees inside of Rust-land. A malformed `DepGraph` could still be introduced through a file unless we do these (rather expensive) checks on every constructed graph.

For me the assumption is that every graph that is valid in the CoNLL-X format should also be a valid `DepGraph`, since we want to be able to read and represent every CoNLL-X file. We could then provide extra functions to check whether `DepGraph` is acyclic, a tree, etc.

> There might still be a problem with verifying the word order. If a user mutated the underlying `DiGraph` through insertion/deletion there is no way to figure out the correct order for this sentence when constructing a `DepGraph`.

Yep, for such cases, we could also provide a constructor where the user can provide a `Vec<NodeIndex>`. So, the default assumption would be: the n-th node index represents the n-th token. I think we can safely do this, since `Graph` stores the nodes in a `Vec`, so the indices are always consecutive. With the mapping this wouldn't be the case and we'd reconstruct the graph so that this invariant holds.

**Comment by sebpuetz** [comment]
>Yep, for such cases, we could also provide a constructor where the user can provide Vec<NodeIndex> (as you suggested above). So, the default assumption would be: the n-th node index represents the n-th token. I think we can safely do this, since Graph stores the nodes in a Vec, so the indices are always consecutive. With the mapping this wouldn't be the case and we'd reconstruct the graph so that this invariant holds.

This means constructing an entirely new graph where the `NodeIndex` is in line with sentence position? 

That would make mutation of the graph structure pretty complex since the user would have to maintain the correct order of the `Vec<NodeIndex>` which to my understanding results in O(n) time for every operation. 
Additionally the graph (re-)construction entails adding the nodes in the correct order and "translating" the edges from the "old" graph into ones compatible with the new graph. 
The first part is rather simple with the `Vec<NodeIndex>`, the second part seems a bit harder to achieve. To get this done I think it's required to also maintain a mapping from the old index to the new index, which is something the `Vec` doesn't offer. This lookup could be constructed while adding the nodes to the new graph.

**Comment by sebpuetz** [comment]
Would this be roughly what you intended? This doesn't include anything about being well-formed but atleast should bring the nodes into the correct order.

```Rust
pub struct DepGraph(Graph<Token, String, Directed>);

impl DepGraph {
    pub fn from_graph(graph: DiGraph<Token, String>, indices: Vec<NodeIndex>) -> Self {
        let (nodes, edges) = graph.into_nodes_edges();
        let mut graph = Graph::with_capacity(nodes.len(), edges.len());
        let mut old_to_new_indices = vec![0usize; nodes.len()];

        for (sent_idx, (old_idx, node)) in indices.iter().zip(nodes.into_iter()).enumerate() {
            old_to_new_indices[old_idx.index()] = sent_idx;
            graph.add_node(node.weight)
        }

        for edge in edges.into_iter() {
            let source = old_to_new_indices[edge.source().index()];
            let target = old_to_new_indices[edge.target().index()];
            let weight = edge.weight;
            graph.add_edge(NodeIndex::new(source), NodeIndex::new(target), weight);
        }

        DepGraph(graph)
    }
}
```

**Comment by danieldk** [comment]
> That would make mutation of the graph structure pretty complex since the user would have to maintain the correct order of the `Vec<NodeIndex>` which to my understanding results in O(n) time for every operation.

Which mutations? Graph indices are stable under most operations. The primary operation that is O(n) is the deletion and removal of tokens. And do you mean *complex* as in time complexity or in programming complexity?

> Additionally the graph (re-)construction entails adding the nodes in the correct order and "translating" the edges from the "old" graph into ones compatible with the new graph.
> The first part is rather simple with the `Vec<NodeIndex>`, the second part seems a bit harder to achieve. To get this done I think it's required to also maintain a mapping from the old index to the new index, which is something the `Vec` doesn't offer.

Yes, indeed, I think you'd need such a mapping to look up the head's index.

**Comment by danieldk** [comment]
> Would this be roughly what you intended? This doesn't include anything about being well-formed but atleast should bring the nodes into the correct order.

Looks about right from a quick read.

> ```rust
>         for (sent_idx, (old_idx, node)) in indices.iter().zip(nodes.into_iter()).enumerate() {
>             old_to_new_indices[old_idx.index()] = sent_idx;
>             graph.add_node(node.weight)
>         }
>```

This seems to add the nodes in the new graph in the same order as the old graph? The nodes should be added in the order of `indices` to have the nodes in sentence order.

>```rust
>         for edge in edges.into_iter() {
>             let source = old_to_new_indices[edge.source().index()];
>             let target = old_to_new_indices[edge.target().index()];
>             let weight = edge.weight;
>             graph.add_edge(NodeIndex::new(source), NodeIndex::new(target), weight);
>         }
>```

Yes, looks good!

*O(|V| + |E|)*

**Comment by sebpuetz** [comment]
> Which mutations? Graph indices are stable under most operations. The primary operation that is O(n) is the deletion and removal of tokens. And do you mean _complex_ as in time complexity or in programming complexity?

Removal and insertion is what I had in mind. After writing it out in actual code it turned out much simpler than expected, so not that complex (logic wise, not time wise) actually.

**Comment by sebpuetz** [comment]
> This seems to add the nodes in the new graph in the same order as the old graph? The nodes should be added in the order of indices to have the nodes in sentence order. 

True, I was trying to figure out a way to move the items out of the `Vec` in the correct order without using `remove()` and messed up on the way. Do you have a suggestion how to achieve this without shifting the contents of the `indices` vector on each iteration? Cloning also seems a bit too heavy, sorting by the new indices might also be overkill.

**Comment by danieldk** [comment]
Maybe you can sort the nodes using the indices? The node indices array states the final position that a node should be in. You'd repeatedly swap the nodes in the correct positions. The you'd have the nodes in the correct order for addition. Whilst doing this, you could also build up the mapping for the edges.

**Comment by sebpuetz** [comment]
This should do the trick then:
```Rust
pub struct DepGraphError(String);

pub struct DepGraph(DiGraph<GraphToken, String>);

impl DepGraph {
    pub fn from_graph(graph: DiGraph<GraphToken, DepRel>, indices: Vec<NodeIndex>) -> Result<Self, DepGraphError>{
        let (mut nodes, edges) = graph.into_nodes_edges();
        let mut old_to_new_indices = vec![0usize; nodes.len()];
        let mut has_head = vec![false; nodes.len()];
        for (sent_idx, old_idx) in indices.iter().map(|idx| idx.index()).enumerate() {
            nodes.swap(old_idx, sent_idx);
            old_to_new_indices[old_idx] = sent_idx;
        }

        let mut graph = Graph::with_capacity(nodes.len(), edges.len());
        for node in nodes.into_iter() {
            graph.add_node(node.weight);
        }

        for edge in edges.into_iter() {
            let source = old_to_new_indices[edge.source().index()];
            let target = old_to_new_indices[edge.target().index()];
            if has_head[target] {
                return Err(DepGraphError("Multiheaded token".to_string()))
            }
            has_head.target = true;
            let weight = edge.weight;
            graph.add_edge(NodeIndex::new(source), NodeIndex::new(target), weight);
        }

        if is_cyclic_directed(&graph) {
            return Err(DepGraphError("Graph contains cycle".to_string()))
        };

        Ok(DepGraph(graph))
    }
}
```

_edit: Added checks to ensure validity of input Graph_

**Comment by danieldk** [comment]
> ```rust
>         for (sent_idx, old_idx) in indices.iter().map(|idx| idx.index()).enumerate() {
>             nodes.swap(old_idx, sent_idx);
>             old_to_new_indices[old_idx] = sent_idx;
>         }
> ```

~~~
Counter-example:

Initial:

nodes:   a b c
indices: 1 2 0

Correct order: b c a

Steps:

0: (0, 1): b a c
1: (1, 2): b c a
2: (2, 0): a c b
~~~

A simple correct implementation would be something along the lines of:

~~~rust
use std::mem;

// Initialize with some cheap bogus value.
let reordered = vec![Node::Root; indices.len()];
for (sent_idx, old_idx) in indices.iter().map(|idx| idx.index()).enumerate() {
    mem::swap(&mut reordered[sent_idx], &mut nodes[old_idx]);
}
~~~

This avoids clones, but there must be some nice way to do it in-place ;). But the indices array would have to be modified as well, since swapping nodes changes their order and invalidates the original indices.

**Comment by sebpuetz** [comment]
> A simple correct implementation would be something along the lines of:
> 
> ```rust
> use std::mem;
> 
> // Initialize with some cheap bogus value.
> let reordered = vec![Node::Root; indices.len()];
> for (sent_idx, old_idx) in indices.iter().map(|idx| idx.index()).enumerate() {
>     mem::swap(&mut reordered[sent_idx], &mut nodes[old_idx]);
> }
> ```
> 
> This avoids clones, but there must be some nice way to do it in-place ;). But the indices array would have to be modified as well, since swapping nodes changes their order and invalidates the original indices.

`nodes` contains `petgraph::Graph::Node` which does not have a public constructor, this would be missing 
```Rust
let nodes = nodes.into_iter().map(|node| node.weight).collect::<Vec<_>>();
```

I think it would be possible to get mutable references into the original graph and use `std::mem::replace` to replace the `conllx::Graph::Node` with `conllx::Graph::Node::Root`. These could directly be added into the new graph. After all the nodes are ported to the new graph we could use `into_nodes_edges()` to get the edge references, make those valid for the new graph and add them.

_edit:_
```Rust
    pub fn from_graph_indices(
        mut graph: DiGraph<Node, String>,
        indices: Vec<NodeIndex>,
    ) -> Result<Self, DepGraphError> {
        let mut ret_graph = Graph::with_capacity(graph.node_count(), graph.edge_count());
        let mut old_to_new_indices = vec![0usize; graph.node_count()];
        for (sent_idx, old_idx) in indices.into_iter().enumerate() {
            ret_graph.add_node(mem::replace(&mut graph[old_idx], Node::Root));
            old_to_new_indices[old_idx.index()] = sent_idx;
        }

        let (_, edges) = graph.into_nodes_edges();
        let mut has_head = vec![false; ret_graph.node_count()];

        for edge in edges.into_iter() {
            let source = old_to_new_indices[edge.source().index()];
            let target = old_to_new_indices[edge.target().index()];
            if has_head[target] {
                return Err(DepGraphError::MultiheadedToken {
                    value: "Multiheaded token".to_string(),
                });
            }
            has_head[target] = true;
            let weight = edge.weight;
            ret_graph.add_edge(NodeIndex::new(source), NodeIndex::new(target), weight);
        }

        if is_cyclic_directed(&ret_graph) {
            return Err(DepGraphError::CyclicGraph {
                value: "Graph contains cycle".to_string(),
            });
        };

        Ok(DepGraph(ret_graph))
    }
```
